#!/bin/sh
set -efu

pythons="$(py3versions -s 2> /dev/null)"

cp -a src/tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for python in $pythons; do
	echo "=== $python ==="
	$python -m pytest tests
done 2>&1
